import { Suspense, lazy, useEffect, useRef } from 'react'
import { motion, useReducedMotion } from 'framer-motion'
import gsap from 'gsap'; import { ScrollTrigger } from 'gsap/ScrollTrigger'
import { skills,projects,education } from './data/content'
import { Nav,Footer,SectionTitle,Magnetic,ArrowDown,ArrowUpRight,Download,MapPin } from './components/UI'
const Scene=lazy(()=>import('./components/Scene'))
gsap.registerPlugin(ScrollTrigger)
function Cursor(){const r=useRef();useEffect(()=>{if(matchMedia('(pointer:coarse)').matches)return;const f=e=>gsap.to(r.current,{x:e.clientX,y:e.clientY,duration:.18});addEventListener('pointermove',f);return()=>removeEventListener('pointermove',f)},[]);return <div ref={r} className="cursor"/>}
function Hero(){const name='Lakshya Khanna';return <section id="home" className="hero"><div className="hero-orb parallax-bg"/><div className="scene parallax-mid"><Suspense fallback={null}><Scene/></Suspense></div><div className="hero-copy parallax-front"><p className="eyebrow">Portfolio · 2026</p><h1 aria-label={name}>{[...name].map((c,i)=><motion.span aria-hidden key={i} initial={{y:'110%',rotate:5}} animate={{y:0,rotate:0}} transition={{delay:.15+i*.045,duration:.65,ease:[.2,.8,.2,1]}}>{c===' '?<>&nbsp;</>:c}</motion.span>)}</h1><p className="tag">B.Tech IT Student <i/> ML / GenAI / Full-Stack Developer</p><p className="hook">Building ML pipelines, LLM-integrated tools, and full-stack apps.</p><div className="cta-row"><Magnetic href="#projects" className="button primary">View Projects <ArrowUpRight/></Magnetic><Magnetic href="/resume.pdf" download className="button glass">Download Resume <Download/></Magnetic></div></div><a href="#about" className="scroll-hint">Scroll to explore <ArrowDown/></a></section>}
function About(){return <section id="about" className="section about"><div className="about-copy"><SectionTitle kicker="01 / About" title={<>Curiosity, turned into <em>working software.</em></>}/><p className="lead reveal">I’m an Information Technology student at GTBIT, GGSIPU, focused on the intersection of machine learning, generative AI, and thoughtful full-stack development.</p><p className="reveal">I build Python ML pipelines, integrate LLMs through Gemini, OpenRouter and Ollama, and ship secure REST-backed experiences. With 5+ end-to-end projects delivered, I’m looking for an ML / AI Engineering internship where ideas become useful systems.</p><div className="facts reveal"><span><MapPin/>Delhi, India</span><span>English · Hindi · Punjabi · German B1</span></div><article className="experience reveal"><b>Top Campus Ambassador</b><span>TRYST’24 · IIT Delhi</span><p>Led social strategy and promotional design for IIT Delhi’s annual technical festival, Jan–Mar 2024.</p></article></div><div className="tech-cluster parallax-mid" aria-hidden><div className="ring r1"/><div className="ring r2"/><div className="core">AI</div>{['ML','API','LLM','PY'].map((x,i)=><span key={x} style={{'--i':i}}>{x}</span>)}</div></section>}
function Skills(){return <section id="skills" className="section"><SectionTitle kicker="02 / Capabilities" title={<>Tools for the <em>whole build.</em></>} copy="From data and models to APIs, interfaces, deployment and hardware."/><div className="skills-grid">{skills.map(([g,items],i)=><motion.article className="skill-card reveal" key={g} whileHover={{y:-8,rotateX:2,rotateY:i%2?2:-2}}><span>0{i+1}</span><h3>{g}</h3><div>{items.map(x=><b key={x}>{x}</b>)}</div></motion.article>)}</div></section>}
function Projects(){return <section id="projects" className="section projects"><SectionTitle kicker="03 / Selected work" title={<>Ideas made <em>tangible.</em></>}/><div className="project-list">{projects.map((p,i)=><motion.article key={p.n} className="project-card reveal" whileHover={{scale:.995}}><div className="project-index">0{i+1}</div><div><p className="project-kind">{p.k}</p><h3>{p.n}</h3><div className="tags">{p.t.map(x=><span key={x}>{x}</span>)}</div></div><ul>{p.d.map(x=><li key={x}>{x}</li>)}</ul>{p.url?<a href={p.url} target="_blank" rel="noreferrer" aria-label={`${p.n} on GitHub`}><ArrowUpRight/></a>:<span className="private">Private build</span>}</motion.article>)}</div></section>}
function Education(){return <section id="education" className="section"><SectionTitle kicker="04 / Education" title={<>Learning without an <em>endpoint.</em></>}/><div className="timeline"><div className="timeline-line"/>{education.map((e,i)=><article className="timeline-item reveal" key={e.title}><i/><time>{e.date}</time><div><span>{e.meta}</span><h3>{e.title}</h3><p>{e.place}</p></div></article>)}</div></section>}
function Publications(){return <section id="publications" className="section publications"><SectionTitle kicker="05 / Publications" title={<>Research in <em>progress.</em></>}/><div className="empty reveal"><span>00</span><h3>Publications — coming soon.</h3><p>Experiments are becoming findings. Future entries will include title, venue, abstract and paper link.</p></div></section>}
export default function App(){const reduced=useReducedMotion();useEffect(()=>{if(reduced)return;const ctx=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:65,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 88%'}}));gsap.utils.toArray('.parallax-bg').forEach(el=>gsap.to(el,{yPercent:35,scale:.85,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.5}}));gsap.utils.toArray('.parallax-mid').forEach(el=>gsap.to(el,{yPercent:20,rotate:3,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1.2}}));gsap.to('.timeline-line',{scaleY:1,ease:'none',scrollTrigger:{trigger:'.timeline',start:'top 70%',end:'bottom 65%',scrub:true}})},document.body);return()=>ctx.revert()},[reduced]);return <><a className="skip" href="#about">Skip to content</a><Cursor/><Nav/><main><Hero/><About/><Skills/><Projects/><Education/><Publications/></main><Footer/></>}
