import {lazy,Suspense,useEffect,useRef} from 'react'
import {Link} from 'react-router-dom'
import {motion,useReducedMotion} from 'framer-motion'
import {FiArrowDown,FiArrowUpRight,FiDownload,FiGithub,FiMail,FiMapPin,FiPhone} from 'react-icons/fi'
import {SiPython,SiNumpy,SiPandas,SiScikitlearn,SiFastapi,SiTailwindcss,SiSupabase,SiPostgresql,SiFirebase,SiMysql,SiGit,SiGithub,SiVercel,SiCloudflare,SiArduino} from 'react-icons/si'
import {Magnetic} from './components/Layout';import {projects,skillGroups,education,courses} from './data/content'
const Scene=lazy(()=>import('./components/Scene'))
const meta={
'/':['Lakshya Khanna — ML / GenAI Developer','ML pipelines, LLM tools, and full-stack applications.'],
'/about':['About — Lakshya Khanna','Information Technology student building ML, GenAI, and full-stack products.'],
'/skills':['Skills — Lakshya Khanna','Python, machine learning, LLMs, APIs, databases, deployment, and embedded systems.'],
'/projects':['Projects — Lakshya Khanna','Selected AI, machine learning, and full-stack projects.'],
'/education':['Education — Lakshya Khanna','Academic education and language study.'],
'/courses':['Courses — Lakshya Khanna','Machine learning and MLOps certifications.'],
'/publications':['Publications — Lakshya Khanna','Research and publications by Lakshya Khanna.'],
'/contact':['Contact — Lakshya Khanna','Contact Lakshya Khanna for ML, AI, and software opportunities.']}
export function SEO({path}){useEffect(()=>{document.title=meta[path][0];document.querySelector('meta[name="description"]').content=meta[path][1]},[path]);return null}
const Head=({n,kids,copy})=><header className="page-head"><span>{n}</span><h1>{kids}</h1>{copy&&<p>{copy}</p>}</header>

export function Home(){const hero=useRef(),reduced=useReducedMotion();useEffect(()=>{if(reduced)return;const move=e=>{const x=e.clientX/innerWidth-.5,y=e.clientY/innerHeight-.5;hero.current?.querySelectorAll('[data-depth]').forEach(el=>{const d=+el.dataset.depth;el.style.transform=`translate3d(${x*d}px,${y*d}px,0)`})};addEventListener('pointermove',move);return()=>removeEventListener('pointermove',move)},[reduced]);return <><SEO path="/"/><section className="home" ref={hero}><div className="image-layer blob-one" data-depth="-20"/><div className="image-layer grid-layer" data-depth="12"/><div className="image-layer orb-layer" data-depth="28"/><div className="home-scene" data-depth="18"><Suspense fallback={null}><Scene/></Suspense></div><div className="home-copy" data-depth="42"><p className="eyebrow">Portfolio · 2026</p><h1 aria-label="Lakshya Khanna">{[...'Lakshya Khanna'].map((c,i)=><motion.span aria-hidden key={i} initial={{y:'110%',rotate:5}} animate={{y:0,rotate:0}} transition={{delay:.12+i*.045,duration:.65,ease:[.2,.8,.2,1]}}>{c===' '?<>&nbsp;</>:c}</motion.span>)}</h1><p className="tagline">B.Tech IT Student <i/> ML / GenAI / Full-Stack Developer</p><p className="hook">Building ML pipelines, LLM-integrated tools, and full-stack apps.</p><div className="actions"><Link className="button primary" to="/projects">View Projects <FiArrowUpRight/></Link><Magnetic className="button glass" href="/resume.pdf" download>Download Resume <FiDownload/></Magnetic></div></div><a className="scroll-cue" href="#home-note">Scroll to discover <FiArrowDown/></a></section><section id="home-note" className="home-note"><span>08 focused pages</span><h2>One practice: turning <em>curiosity into systems.</em></h2><Link to="/about">Enter the portfolio <FiArrowUpRight/></Link></section></>}

export function About(){return <><SEO path="/about"/><section className="page split"><div><Head n="01 / About" kids={<>Curiosity, made <em>useful.</em></>}/><p className="lead">I’m an Information Technology student at GTBIT, GGSIPU in Delhi, building at the intersection of machine learning, generative AI, and full-stack engineering.</p><p className="muted">My work spans Python ML pipelines, LLM integrations through Gemini, OpenRouter and Ollama, and secure REST APIs. After shipping 5+ end-to-end projects, I’m seeking an ML / AI Engineering internship where experimentation becomes reliable software.</p><div className="fact-grid"><article><FiMapPin/><b>Delhi, India</b><span>Location</span></article><article><b>English · Hindi · Punjabi · German</b><span>Professional · Native · Native · B1</span></article></div><article className="experience"><span>Jan — Mar 2024</span><h3>Top Campus Ambassador · TRYST’24</h3><p>IIT Delhi’s annual technical festival. Led social strategy and promotional design, increasing visibility and student registrations; recognized with a Letter of Recommendation and Certificate.</p></article></div><div className="about-visual" aria-label="Abstract three dimensional artificial intelligence form"><Suspense fallback={<div className="loader"/>}><Scene/></Suspense><div className="orbit-labels"><span>ML</span><span>API</span><span>LLM</span><span>PY</span></div></div></section></>}

const iconMap={Python:SiPython,NumPy:SiNumpy,Pandas:SiPandas,'Scikit-Learn':SiScikitlearn,FastAPI:SiFastapi,'Tailwind CSS':SiTailwindcss,Supabase:SiSupabase,PostgreSQL:SiPostgresql,Firebase:SiFirebase,MySQL:SiMysql,Git:SiGit,GitHub:SiGithub,Vercel:SiVercel,Cloudflare:SiCloudflare,'Arduino UNO':SiArduino}
export function Skills(){return <><SEO path="/skills"/><section className="page"><Head n="02 / Skills" kids={<>A futuristic <em>toolkit.</em></>} copy="Models, interfaces, infrastructure, and hardware—organized as a living system."/><div className="skill-bento">{skillGroups.map(([group,items],i)=><motion.article key={group} className={`skill-group s${i}`} whileHover={{y:-8,rotateX:2,rotateY:i%2?2:-2}}><header><span>0{i+1}</span><h2>{group}</h2></header><div>{items.map(item=>{const Icon=iconMap[item];return <motion.span key={item} className="skill-chip" whileHover={{scale:1.08}}>{Icon?<Icon aria-hidden/>:<b>{item.slice(0,2).toUpperCase()}</b>}<small>{item}</small></motion.span>})}</div></motion.article>)}</div></section></>}

export function Projects(){return <><SEO path="/projects"/><section className="page"><Head n="03 / Projects" kids={<>Selected <em>builds.</em></>} copy="Three systems spanning agentic product design, behavioral ML, and privacy-first browser AI."/><div className="project-grid">{projects.map((p,i)=><motion.article key={p.n} className="project-card" whileHover={{y:-10,rotateX:1.5,rotateY:i%2?1.5:-1.5}}><div className="project-top"><span>0{i+1}</span>{p.url?<a href={p.url} target="_blank" rel="noreferrer" aria-label={`${p.n} GitHub repository`}><FiGithub/><FiArrowUpRight/></a>:<small>Private build</small>}</div><p>{p.k}</p><h2>{p.n}</h2><div className="tags">{p.t.map(x=><span key={x}>{x}</span>)}</div><ul>{p.d.map(x=><li key={x}>{x}</li>)}</ul></motion.article>)}</div></section></>}

function CardsPage({type}){const isEdu=type==='education',data=isEdu?education:courses;return <><SEO path={`/${type}`}/><section className="page"><Head n={isEdu?'04 / Education':'05 / Courses'} kids={isEdu?<>Academic <em>foundations.</em></>:<>Continuous <em>learning.</em></>} copy={isEdu?'Formal study across technology and language.':'Focused training that strengthens applied ML and production engineering.'}/><div className="clean-cards">{data.map((x,i)=><motion.article key={x.title} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:i*.12}}><span>{x.date}</span><small>{x.status||x.type}</small><h2>{x.title}</h2>{x.subject&&<h3>{x.subject}</h3>}<p>{x.place}</p></motion.article>)}</div></section></>}
export const Education=()=> <CardsPage type="education"/>;export const Courses=()=> <CardsPage type="courses"/>
export function Publications(){return <><SEO path="/publications"/><section className="page"><Head n="06 / Publications" kids={<>Research in <em>progress.</em></>}/><div className="publication-empty"><span>00</span><div><p>Knowledge wants to be shared.</p><h2>Publications — coming soon.</h2><small>Future entries will use reusable title, venue, summary, and paper-link fields.</small></div></div></section></>}
export function Contact(){return <><SEO path="/contact"/><section className="page contact-page"><p className="eyebrow">07 / Contact</p><h1>Let’s <em>Talk.</em></h1><p>Have an internship, collaboration, or difficult technical problem in mind? My inbox is open.</p><div className="contact-links"><Magnetic href="mailto:Lakshya1khanna@gmail.com"><FiMail/><span>Email</span><small>Lakshya1khanna@gmail.com</small></Magnetic><Magnetic href="tel:+917042023024"><FiPhone/><span>Phone</span><small>+91 70420 23024</small></Magnetic><Magnetic href="https://github.com/Lakshya-Khanna-1" target="_blank" rel="noreferrer"><FiGithub/><span>GitHub</span><small>@Lakshya-Khanna-1</small></Magnetic><span className="contact-disabled" title="Add your LinkedIn profile URL"><FiArrowUpRight/><b>LinkedIn</b><small>URL not provided</small></span></div><form action="mailto:Lakshya1khanna@gmail.com" method="post" encType="text/plain"><label>Name<input name="name" required/></label><label>Email<input type="email" name="email" required/></label><label className="wide">Message<textarea name="message" rows="4" required/></label><button>Open in email app <FiArrowUpRight/></button></form><footer>© {new Date().getFullYear()} Lakshya Khanna · Designed and built with intent.</footer></section></>}
